version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - todo_network

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/todo_db
      JWT_SECRET: your_secret_key
      WEATHER_API_KEY: f88022c30ee50cead5b2e92d1082e59f
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    networks:
      - todo_network

volumes:
  db_data:

networks:
  todo_network:
    driver: bridge
